export const tokens = {
  colors: {
    primary: '#D9381E',
    primaryDark: '#B32610',
    primaryLight: '#FFECE8',
    background: '#FAFAFA',
    card: '#FFFFFF',
    border: '#E6E0E9',
    textPrimary: '#1C1B1F',
    textSecondary: '#49454F',
    textMuted: '#79747E',
    white: '#FFFFFF',
    status: {
      greenText: '#146C2E',
      greenBg: '#DFF6E5',
      redText: '#B3261E',
      redBg: '#F9DEDC',
      orangeText: '#B25E00',
      orangeBg: '#FFF3E0',
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
  },
  radii: {
    sm: 8,
    md: 12,
    lg: 16,
    full: 9999,
  },
  typography: {
    fontXs: 11,
    fontSm: 13,
    fontMd: 15,
    fontLg: 17,
    fontXl: 20,
    fontXxl: 24,
  },
} as const;
