// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestauranteInteligente.Infrastructure.Persistence;

#nullable disable

namespace RestauranteInteligente.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001021910_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.Assinatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("DataExpiracao")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("DataFimTrial")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("DataInicio")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("PlanoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("PlanoId")
                        .HasDatabaseName("IX_Assinaturas_PlanoId");

                    b.HasIndex("RestauranteId")
                        .IsUnique()
                        .HasDatabaseName("IX_Assinaturas_RestauranteId");

                    b.ToTable("Assinaturas", (string)null);
                });

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.DadosClimaticos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ConsultadoEm")
                        .HasColumnType("timestamptz");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<decimal>("Precipitacao")
                        .HasColumnType("numeric(6,2)");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Temperatura")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("TipoDado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Umidade")
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId", "Data")
                        .IsUnique()
                        .HasDatabaseName("UQ_DadosClimaticos_Restaurante_Data");

                    b.ToTable("DadosClimaticos", (string)null);
                });

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.FechamentoCaixa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("DataAbertura")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("DataFechamento")
                        .HasColumnType("timestamptz");

                    b.Property<int>("QuantidadeVendas")
                        .HasColumnType("integer");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalVendas")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("ValorTotalVendas");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId")
                        .IsUnique()
                        .HasDatabaseName("IX_FechamentosCaixa_Ativo")
                        .HasFilter("\"Status\" = 'ABERTO'");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_FechamentosCaixa_UsuarioId");

                    b.ToTable("FechamentosCaixa", (string)null);
                });

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.Insumo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz");

                    b.Property<decimal>("CustoUnitario")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("EstoqueMinimo")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("QuantidadeEstoque")
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId", "Nome")
                        .IsUnique();

                    b.ToTable("Insumos", (string)null);
                });

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.ItemVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("IX_ItensVenda_ProdutoId");

                    b.HasIndex("RestauranteId")
                        .HasDatabaseName("IX_ItensVenda_RestauranteId");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("IX_ItensVenda_VendaId");

                    b.ToTable("ItensVenda", (string)null);
                });

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.MovimentacaoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DataHora")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("InsumoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid?>("ReferenciaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId", "InsumoId", "DataHora")
                        .HasDatabaseName("IX_Movimentacoes_Restaurante_Insumo_Data");

                    b.ToTable("MovimentacoesEstoque", (string)null);
                });

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.Plano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("PossuiModuloIa")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PrecoMensal")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("UQ_Planos_Nome");

                    b.ToTable("Planos", (string)null);
                });

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.Previsao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz");

                    b.Property<DateOnly>("DataPrevisao")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataReferencia")
                        .HasColumnType("date");

                    b.Property<string>("ModeloVersao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantidadePrevista")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("DemandaPrevista");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("RestauranteId", "DataPrevisao")
                        .HasDatabaseName("IX_Previsoes_Restaurante_Data");

                    b.HasIndex("RestauranteId", "DataPrevisao", "ProdutoId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Previsoes_Restaurante_Data_Produto");

                    b.ToTable("Previsoes", (string)null);
                });

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId", "Nome");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.ProdutoInsumo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InsumoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantidadeInsumo")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("Quantidade");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InsumoId")
                        .HasDatabaseName("IX_ProdutosInsumos_InsumoId");

                    b.HasIndex("RestauranteId")
                        .HasDatabaseName("IX_ProdutosInsumos_RestauranteId");

                    b.HasIndex("ProdutoId", "InsumoId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ProdutosInsumos_Composicao");

                    b.ToTable("ProdutosInsumos", (string)null);
                });

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.Restaurante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric(10,8)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric(11,8)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("Restaurantes", (string)null);
                });

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Usuarios_Email");

                    b.HasIndex("RestauranteId")
                        .HasDatabaseName("IX_Usuarios_RestauranteId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("DataHora")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("FechamentoCaixaId")
                        .HasColumnType("uuid");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FechamentoCaixaId")
                        .HasDatabaseName("IX_Vendas_FechamentoCaixaId");

                    b.HasIndex("RestauranteId", "DataHora")
                        .HasDatabaseName("IX_Vendas_Restaurante_DataHora");

                    b.ToTable("Vendas", (string)null);
                });

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.Assinatura", b =>
                {
                    b.HasOne("RestauranteInteligente.Domain.Entities.Plano", null)
                        .WithMany()
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RestauranteInteligente.Domain.Entities.Restaurante", null)
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.DadosClimaticos", b =>
                {
                    b.HasOne("RestauranteInteligente.Domain.Entities.Restaurante", null)
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.FechamentoCaixa", b =>
                {
                    b.HasOne("RestauranteInteligente.Domain.Entities.Restaurante", null)
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestauranteInteligente.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.ItemVenda", b =>
                {
                    b.HasOne("RestauranteInteligente.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestauranteInteligente.Domain.Entities.Venda", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.Previsao", b =>
                {
                    b.HasOne("RestauranteInteligente.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestauranteInteligente.Domain.Entities.Restaurante", null)
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.ProdutoInsumo", b =>
                {
                    b.HasOne("RestauranteInteligente.Domain.Entities.Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestauranteInteligente.Domain.Entities.Produto", "Produto")
                        .WithMany("FichaTecnica")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insumo");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("RestauranteInteligente.Domain.Entities.Restaurante", null)
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.Venda", b =>
                {
                    b.HasOne("RestauranteInteligente.Domain.Entities.FechamentoCaixa", null)
                        .WithMany()
                        .HasForeignKey("FechamentoCaixaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RestauranteInteligente.Domain.Entities.Restaurante", null)
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.Produto", b =>
                {
                    b.Navigation("FichaTecnica");
                });

            modelBuilder.Entity("RestauranteInteligente.Domain.Entities.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
